 # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
 # Initialization code that may require console input (password prompts, [y/n]
 # confirmations, etc.) must go above this block; everything else may go below.
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 export BROWSER='/home/athulcd/.local/chrome'
 ## Options section
 setopt correct                                                  # Auto correct mistakes
 setopt extendedglob                                             # Extended globbing. Allows using regular expression    s with *
 setopt nocaseglob                                               # Case insensitive globbing
 setopt rcexpandparam                                            # Array expension with parameters
 setopt nocheckjobs                                              # Don't warn about running processes when exiting
 setopt numericglobsort                                          # Sort filenames numerically when it makes sense
 setopt nobeep                                                   # No beep
 setopt appendhistory                                            # Immediately append history instead of overwriting
 setopt histignorealldups                                        # If a new command is a duplicate, remove the older     one
 setopt autocd                                                   # if only directory path is entered, cd there.
 
 zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
 zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/file    s/etc)
 zstyle ':completion:*' rehash true                              # automatically find new executables in path
 # Speed up completions
 zstyle ':completion:*' accept-exact '*(N)'
 zstyle ':completion:*' use-cache on

 bindkey '^[[B' history-substring-search-down

 # Apply different settigns for different terminals
 case $(basename "$(cat "/proc/$PPID/comm")") in
   login)
       RPROMPT="%{$fg[red]%} %(?..[%?])"
       alias x='startx ~/.xinitrc'      # Type name of desired desktop after x, xinitrc is configured for it
     ;;
#  'tmux: server')
#        RPROMPT='$(git_prompt_string)'
 #   ## Base16 Shell color themes.
 #   #possible themes: 3024, apathy, ashes, atelierdune, atelierforest, atelierhearth,
 #   #atelierseaside, bespin, brewer, chalk, codeschool, colors, default, eighties,
 #   #embers, flat, google, grayscale, greenscreen, harmonic16, isotope, londontube,
 #   #marrakesh, mocha, monokai, ocean, paraiso, pop (dark only), railscasts, shapesifter,
 #   #solarized, summerfruit, tomorrow, twilight
 #   #theme="eighties"
#   #Possible variants: dark and light
#   #shade="dark"
 #   #BASE16_SHELL="/usr/share/zsh/scripts/base16-shell/base16-$theme.$shade.sh"
 #   #[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
 #   # Use autosuggestion
 #   source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
 #   ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
 #     ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
 #     ;;
   *)
        RPROMPT='$(git_prompt_string)'
     # Use autosuggestion
     source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
     ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
     ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
    ;;
esac
source ~/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
 [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

   # If inside a Git repository, print its branch and state
  [ -n "$git_where" ] && echo "$GIT_PROMPT_SYMBOL$(parse_git_state)$GIT_PROMPT_PREFIX%{$fg[yellow]%}${git_where#(refs/heads/|tags/)}$GIT_PROMPT_SUFFIX"

  # If not inside the Git repo, print exit codes of last command (only if it failed)
   [ ! -n "$git_where" ] && echo "%{$fg[red]%} %(?..[%?])"
 }

143 # Right prompt with exit status of previous command if not successful
144  #RPROMPT="%{$fg[red]%} %(?..[%?])"
145 # Right prompt with exit status of previous command marked with ✓ or ✗
146  #RPROMPT="%(?.%{$fg[green]%}✓ %{$reset_color%}.%{$fg[red]%}✗ %{$reset_color%})"

 # Color man pages
 export LESS_TERMCAP_mb=$'\E[01;32m'
 export LESS_TERMCAP_md=$'\E[01;32m'
 export LESS_TERMCAP_me=$'\E[0m'
 export LESS_TERMCAP_se=$'\E[0m'
 export LESS_TERMCAP_so=$'\E[01;47;34m'
 export LESS_TERMCAP_ue=$'\E[0m'
 export LESS_TERMCAP_us=$'\E[01;36m'
 export LESS=-r

 ## Plugins section: Enable fish style features
#Use syntax highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
 # Use history substring search
 source ~/.zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
# bind UP and DOWN arrow keys to history substring search
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
 bindkey '^[[B' history-substring-search-down

 bindkey '^[[B' history-substring-search-down

 # Apply different settigns for different terminals
 case $(basename "$(cat "/proc/$PPID/comm")") in
 login)
     RPROMPT="%{$fg[red]%} %(?..[%?])"
      alias x='startx ~/.xinitrc'      # Type name of desired desktop after x, xinitrc is configured for it
     ;;
 #  'tmux: server')
#        RPROMPT='$(git_prompt_string)'
 #   ## Base16 Shell color themes.
 #   #possible themes: 3024, apathy, ashes, atelierdune, atelierforest, atelierhearth,
#   #atelierseaside, bespin, brewer, chalk, codeschool, colors, default, eighties,
#   #embers, flat, google, grayscale, greenscreen, harmonic16, isotope, londontube,
#   #marrakesh, mocha, monokai, ocean, paraiso, pop (dark only), railscasts, shapesifter,
 #   #solarized, summerfruit, tomorrow, twilight
#   #theme="eighties"
#   #Possible variants: dark and light
 #   #shade="dark"
#   #BASE16_SHELL="/usr/share/zsh/scripts/base16-shell/base16-$theme.$shade.sh"
#   #[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
#   # Use autosuggestion
#   source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
#   ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
#     ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
#     ;;
   *)
         RPROMPT='$(git_prompt_string)'
     # Use autosuggestion
     source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
     ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
     ;;
esac
source ~/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
